
services:
  mysql:
    image: mysql:8.0
    container_name: bucket-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: bucket
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:latest
    container_name: bucket-redis
    ports:
      - "6379:6379"
